### PR TITLE
Rename demo_lcd_simple_strings.py to demo_lcd.py

### PR DESCRIPTION
**Pull request by Kyuchumimo**

### CODE REVIEW

**Review by cgomesu — CHANGES_REQUESTED** [review]
1. the change was introduced by @juvus and I assume that the reasoning was to make a distinction with the new demo they created called `demo_lcd_extended_strings.py`, which was merged to master by 1d5fb18490639b1b7d07cbec74be2c804ffc9326 .

2. the Youtube video tutorial refers to a file that does not exist anymore as a result of 1d5fb18490639b1b7d07cbec74be2c804ffc9326 .  

3. the proposed solution is reasonable.  however, @Kyuchumimo , please **double check** that `demo_lcd_simple_strings.py` is not mentioned anywhere else in the repo (e.g., `README.md`, `demo_*.py`, and so on).

**Comment by Kyuchumimo** [comment]
`README.md`
```
30 ... # Demos
31 ... ## Simple strings
32 ... This is a demo developed by user @Tomtom0201, showing how simple text stings could be displayed on LCD:
```

**Review by Kyuchumimo — COMMENTED** [review]
demo_lcd_**simple_strings**.py

This file is only mentioned here:

```README.md```
```
30 ... # Demos
31 ... ## Simple strings
32 ... This is a demo developed by user @Tomtom0201, showing how simple text stings could be displayed on LCD:
```

**Comment by cgomesu** [comment]
> demo_lcd_**simple_strings**.py
> 
> This file is only mentioned here:
> 
> `README.md`
> 
> ```
> 30 ... # Demos
> 31 ... ## Simple strings
> 32 ... This is a demo developed by user @Tomtom0201, showing how simple text stings could be displayed on LCD:
> ```

okay.  make the changes to the `README.md` file in your branch, stage, and commit.

**Review by cgomesu — APPROVED** [review]
thanks for following up.  I agree with the changes.

**Comment by cgomesu** [comment]
will wait until **Nov 10th** to merge if no one opposes the changes.

of note, once this get merged, I plan on reorganizing the `README.md` file in light of #38.

**Pull request merged**
