### PR TITLE
IP Address Demo

### PR DESCRIPTION
**Pull request by Sierra007117**
Huge fan of your work,love what you've done with the RPi. Here's a little demo code i wrote based on your existing work that shows time and IP address.Please consider it.Thank you.

### CODE REVIEW

**Comment by the-raspberry-pi-guy** [comment]
Awesome stuff! I'll merge this up straight away - just wondering if you have a GIF or demo image that I could add to the README with a shoutout to you too?

Thanks :)

**Comment by Sierra007117** [comment]
WeChat Image_20200728164948
WeChat Image_20200728164954
Glad that you liked it. Here are two demo images. Thanks a lot for allowing me to contribute.

**Comment by the-raspberry-pi-guy** [comment]
Great - thanks!

**Comment by the-raspberry-pi-guy** [comment]
You are in the README now too :)

**Pull request merged**
