### PR TITLE
Updated functionality of the library.

### PR DESCRIPTION
**Pull request by juvus**
Hi,

The functionality of the library was updated in the followings ways:
1) It is possible now to use so-called extended strings. An extended string can contain a special placeholder (for exmaple {0xFF}) with hex code of any symbol in characters table. So, it is possible to print such symbols, that can't be entered using keyboard only.
2) It is now possible to determine 8 custom characters and print them with help of placeholders in the extended strings. 
3) Added some demos showing how the extended strings with placeholders can be used as well as how it is possible to define own custom characters;
4) A bit updated README.md file

Best Regards,
juvus

### CODE REVIEW

**Comment by the-raspberry-pi-guy** [comment]
This looks like a good set of functionality to add to the library - thank you. I don't have an LCD to check this with anymore, would you be able to confirm that all of the previous demos and functionality still work? I am happy to merge as long as nothing else is broken by this.

Thanks again

**Comment by juvus** [comment]
Hi, Matt!

Thank you for responce :)

Since I haven't changed names or functionalily of previous functions/methods they work the same way. I have tested one more time all set of demos on both LCDs - on 1602A (2 lines, 16 cols) and 2004A (4 lines, 20 cols) and the work smoothly. In my 2 las commits i tried also to polish 2 demos a bit:

1) demo_forex.py - a bit revised the main loop. Now it is possible to terminate the program with Ctrl+C as it is in other demos. 
2) demo_scrolling_text.py - I put the defauls value for columns to 16 in long_string function because, I guess, a new 16x2 displays are more popular. Don't know actually, but I have this feelings :). 

I also have a strong feeling, that function long_string in "demo_scrolling_text.py" should be a part of the i2c_dev.py, because it represents a nice functionality of the library. But I guess this is an issue of futher development :)

BR,
juvus

**Comment by the-raspberry-pi-guy** [comment]
Cool stuff - thanks for your diligent work. Happy to take everything on face value and merge it as I don't have the capability to also test. I have had a peruse through the code and it looks good. Thanks again for contributing.

**Comment by cgomesu** [comment]
very cool.  did not know about the custom characters and think the changes are reasonable.  thanks, @juvus !

**Comment by the-raspberry-pi-guy** [comment]
Thanks for chipping in @cgomesu - good to have another pair of eyes 👀

**Comment by juvus** [comment]
Thanks, @the-raspberry-pi-guy ! :) Hope it will help people studying raspberry to make their projects better and more interesting! Yes @cgomesu, but you have only 64 bytes for this CG RAM. It means that by using 8 bytes per symbol it is possible to define only 8 custom characters at a time -> it means that no more than 8 unique characters can be displayed at the same time (as I understand from the datasheet).
BR, 
juvus

**Pull request merged**
