### PR TITLE
Bring demo_forex.py back (Fixed fetching currencies)

### PR DESCRIPTION
**Pull request by Kubzelll**

### CODE REVIEW

**Comment by cgomesu** [comment]
just a heads up that I'm particularly busy this week, so it might take a while to review your pr. however, I'll try to take a look at it over the upcoming weekend. hang in there.

**Review by cgomesu — COMMENTED** [review]
there were a couple of issues with the forex demo that were mentioned in #65. how did you address them?

**Comment by Kubzelll** [comment]
Hello, I changed the address that will data be scraped from https://tr.investing.com/ to https://www.investing.com/currencies/ because the table with exchange rate was on this address, and i also changed the scraping because

**Comment by cgomesu** [comment]
okay. there was an import issue but I've already fixed it. I think we're all good here. thanks for the contribution and congrats on your first successful PR, @Kubzelll . :rocket:

**Pull request merged**
